#%RAML 1.0
title: Healthcare API
version: 1.0

types:
  Patient:
    properties:
      name: string
      gender?: string
      birthDate?: date-only | datetime
      address?: string

mediaType:
  - application/fhir+xml; fhirVersion=4.0
  - application/fhir+json; fhirVersion=4.0
  - application/xml; charset=iso-8859-1
  - application/json; charset=iso-8859-1

/Patient/{id}:
  get:
    responses:
      200:
        body:
          type: Patient

  put:
    body:
      type: Patient
    responses:
      200: