#%RAML 1.0
version: api
title: testing-api
baseUri: http://localhost:24008/api


/multiple-values-in-uri-params/{division}_{category}_{group}:
  get:
     responses:
        200:
          body:
            application/json:
